import type { Metadata } from "next";
import { Providers } from "../providers";
import "../globals.css";
import { SidebarInset, SidebarProvider } from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/app-sidebar";
import { AppHeader } from "@/components/app-header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export interface DashboardLayoutProps {
  children: React.ReactNode;
}

export default function DashboardLayout({ children }: DashboardLayoutProps) {
  return (
    <Providers>
      <SidebarProvider>
        <AppSidebar />
        <SidebarInset>
          <AppHeader />
          <div className="min-h-screen pt-12 transition-all ease-linear group-has-data-[collapsible=icon]/sidebar-wrapper:pt-12">
            {children}
          </div>
        </SidebarInset>
      </SidebarProvider>
    </Providers>
  );
}
